# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  APP_ENV: ${{ vars.APP_ENV }}
  PORT: ${{ vars.PORT }}
  VENDURE_API_URL: ${{ vars.VENDURE_API_URL }}

jobs:
  build-backend:

    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Create env file
      run: |
          touch .env
          echo APP_ENV=${{ vars.APP_ENV }} >> .env
          echo PORT=${{ vars.PORT }} >> .env
          echo VENDURE_API_URL=${{ vars.VENDURE_API_URL }} >> .env
    - name: Build App
      run: npm install && env $(cat .env | grep -v \"#\" | xargs) pm2 startOrReload start.json
